// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RoleSelect: typeof import('./../src/components/Select/RoleSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RzAreaLazySelect: typeof import('./../src/components/RzCommon/RzAreaLazySelect/index.vue')['default']
    RzAreaSelect: typeof import('./../src/components/RzCommon/RzAreaSelect/index.vue')['default']
    RzDrawer: typeof import('./../src/components/RzCommon/RzDrawer/index.vue')['default']
    RzEditor: typeof import('./../src/components/RzCommon/RzEditor/index.vue')['default']
    RzNumberInput: typeof import('./../src/components/RzCommon/RzNumberInput/index.vue')['default']
    RzTableSelect: typeof import('./../src/components/RzCommon/RzTableSelect/index.vue')['default']
    RzTitle: typeof import('./../src/components/RzCommon/RzTitle/index.vue')['default']
    RzUploadFile: typeof import('./../src/components/RzCommon/RzUploadFile/index.vue')['default']
    RzUploadImg: typeof import('./../src/components/RzCommon/RzUploadImg/index.vue')['default']
  }
}
