// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RoleSelect: typeof import('./../src/components/Select/RoleSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RzDrawer: typeof import('./../src/components/RzCommon/RzDrawer/index.vue')['default']
    RzTitle: typeof import('./../src/components/RzCommon/RzTitle/index.vue')['default']
    RzUpload: typeof import('./../src/components/RzCommon/RzUpload/index.vue')['default']
  }
}
